### ISSUE TITLE
[TASK] Compute numerical chain_id (u32) for cosmos chains

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-cosmwasm#39]

**Comment by duguorong009** [comment]
@shekohex @drewstone 
I think we already had some discussion about this topic - `how to convert string chain_id into numeric`.
I remember @shekohex suggested a solution like:
 - Hash the `chain_id` of blockchain
     eg: keccak256("juno-1")
 - Slice the last last 4 bytes & convert to `u32` numeric value

@shekohex 
can you please confirm the solution & document it in the current `webb-proposal` doc?
